// data.js

const mockScripts = [
  {
    targetCategory: "All",
    situation: { ko: "주문할 때", en: "When Ordering", uz: "Buyurtma berishda", ur: "آرڈر کرتے وقت", mn: "Захиалах үед", ne: "अर्डर गर्दा", vi: "Khi gọi món", si: "ඇණවුම් කරන විට" },
    scripts: [
      {
        ko: "이거 하나 주세요.", pronunciation: "Igeo hana juseyo.",
        en: "I'll have one of this, please.",
        uz: "Iltimos, bundan bitta bering.",
        ur: "براہ کرم مجھے یہ ایک دے دیں۔",
        mn: "Энэнээс нэгийг өгөөч.",
        ne: "मलाई यो एउटा दिनुहोस्।",
        vi: "Cho tôi một cái này.",
        si: "කරුණාකර මට මෙය එකක් දෙන්න."
      },
      {
        ko: "포장해 주세요.",
        en: "To go, please.",
        uz: "Olib ketishga.",
        ur: "لے جانے کے لئے.",
        mn: "Савлаад өгөөч.",
        ne: "प्याक गरिदिनुहोस्।",
        vi: "Cho tôi mang đi.",
        si: "කරුණාකර ගෙන යාමට දෙන්න."
      }
    ]
  },
  {
    targetCategory: "Restaurant",
    situation: { ko: "알레르기/요청사항", en: "Allergies & Requests", uz: "Allergiya va so'rovlar", ur: "الرجی اور درخواستیں", mn: "Харшил / Хүсэлт", ne: "एलर्जी र अनुरोधहरू", vi: "Dị ứng & Yêu cầu", si: "අසාත්මිකතා සහ ඉල්ලීම්" },
    scripts: [
      {
        ko: "고기 빼주세요.",
        en: "No meat, please.",
        uz: "Go'shtsiz, iltimos.",
        ur: "بغیر گوشت کے، براہ کرم.",
        mn: "Махгүй хийгээрэй.",
        ne: "मासु नराख्नुहोस्।",
        vi: "Không thịt nhé.",
        si: "මස් එපා, කරුණාකර."
      },
      {
        ko: "맵지 않게 해주세요.",
        en: "Not spicy, please.",
        uz: "Achchiq bo'lmasin, iltimos.",
        ur: "مسالہ دار نہیں، براہ کرم.",
        mn: "Халуун ногоогүй хийгээрэй.",
        ne: "पिरो नबनाउनुहोस्।",
        vi: "Không cay nhé.",
        si: "සැර නැතිව කරුණාකර."
      }
    ]
  },
  {
    targetCategory: "Restaurant",
    situation: { ko: "식당에서 (Restaurant)", en: "At the Restaurant", uz: "Restoranda", ur: "ریستوراں میں", mn: "Ресторанд", ne: "रेस्टुरेन्टमा", vi: "Tại Nhà hàng", si: "ආපනශාලාවේ" },
    scripts: [
      {
        ko: "화장실이 어디예요?",
        en: "Where is the restroom?",
        uz: "Hojatxona qayerda?",
        ur: "باتھ روم کہاں ہے؟",
        mn: "Ариун цэврийн өрөө хаана вэ?",
        ne: "शौचालय कहाँ छ?",
        vi: "Nhà vệ sinh ở đâu?",
        si: "වැසිකිළිය කොහෙද?"
      },
      {
        ko: "반찬 좀 더 주시겠어요?",
        en: "Can I get some more side dishes?",
        uz: "Yana ozgina yon ovqatlar olsam bo'ladimi?",
        ur: "کیا مجھے کچھ اور سائیڈ ڈشز مل سکتی ہیں؟",
        mn: "Хачир нэмж болох уу?",
        ne: "के म अझै केही साइड डिशहरू पाउन सक्छु?",
        vi: "Cho tôi thêm một ít món ăn kèm nhé?",
        si: "මට තව අමතර කෑම ටිකක් ලබා ගත හැකිද?"
      },
      {
        ko: "계산할게요. / 영수증 주세요.",
        en: "I would like to pay. / Receipt, please.",
        uz: "Men to'lamoqchiman. / Chek bering, iltimos.",
        ur: "میں ادائیگی کرنا چاہتا ہوں۔ / رسید، براہ کرم.",
        mn: "Тооцоо хийе. / Баримт өгөөч.",
        ne: "म पैसा तिर्न चाहन्छु। / रसिद दिनुहोस्।",
        vi: "Tôi muốn thanh toán. / Cho tôi hóa đơn.",
        si: "මම ගෙවන්න කැමතියි. / බිල්පත කරුණාකර."
      }
    ]
  },
  {
    targetCategory: "Cafe",
    situation: { ko: "카페에서 (Cafe)", en: "At the Cafe", uz: "Kafeda", ur: "کیفے میں", mn: "Кафед", ne: "क्याफेमा", vi: "Tại Quán cà phê", si: "කැෆේහි" },
    scripts: [
      {
        ko: "먹고 갈게요. (매장 식사)",
        en: "For here, please.",
        uz: "Shu yerda yeyman.",
        ur: "یہاں کے لئے، براہ کرم.",
        mn: "Энд иднэ.",
        ne: "यहाँ खानको लागि.",
        vi: "Dùng tại quán.",
        si: "මෙහේ කෑමට."
      },
      {
        ko: "따뜻한 걸로 주세요. / 아이스로 주세요.",
        en: "Hot, please. / Iced, please.",
        uz: "Issiq, iltimos. / Muzli, iltimos.",
        ur: "گرم، براہ کرم. / آئسڈ، براہ کرم.",
        mn: "Халуунаар нь өгөөч. / Мөстэйг өгөөч.",
        ne: "तातो दिनुहोस्। / चिसो दिनुहोस्।",
        vi: "Cho đồ uống nóng. / Cho đồ uống đá.",
        si: "උණුසුම් කරුණාකර. / අයිස් කරුණාකර."
      },
      {
        ko: "연하게 타주세요. (샷 하나 빼주세요)",
        en: "Make it mild, please. (Only one shot)",
        uz: "Kuchsiz qiling, iltimos.",
        ur: "اسے ہلکا بنائیں، براہ کرم.",
        mn: "Зөөлөн найруулж өгөөч.",
        ne: "नरम बनाउनुहोस्।",
        vi: "Làm nhạt thôi nhé.",
        si: "සැර අඩුවෙන් හදන්න."
      }
    ]
  }
];

const mockRestaurants = [
  {
    id: 5,
    name_ko: "원광카츠 원광대점",
    name_en: "Wonkwang Katsu",
    category: "Restaurant",
    reviewCount: 412,
    hearts: 1050,
    locationType: "out-campus",
    emoji: "🍱",
    coverImage: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 93",
    hours: "10:00 - 20:00 (토 휴무)",
    breakTime: "15:00 - 16:30",
    mapNaver: "https://map.naver.com/p/search/%EC%9B%90%EA%B4%91%EC%B9%B4%EC%B8%A0%20%EC%9B%90%EA%B4%91%EB%8C%80%EC%A0%90/place/1120792731",
    mapGoogle: "https://www.google.com/maps/search/%EC%9B%90%EA%B4%91%EC%B9%B4%EC%B8%A0+%EC%9B%90%EA%B4%91%EB%8C%80%EC%A0%90",
    menu: [
      { name: "옛추억의 왕돈까스", desc: { ko: "옛날식 왕돈까스와 달콤한 소스", en: "Classic large tonkatsu" }, price: "11,000원", image: "https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=200&q=80" },
      { name: "등심숙성돈까스", desc: { ko: "", en: "" }, price: "10,000원", image: "" },
      { name: "안심숙성돈까스", desc: { ko: "", en: "" }, price: "11,000원", image: "" },
      { name: "치즈돈까스", desc: { ko: "", en: "" }, price: "12,000원", image: "" },
      { name: "고구마치즈돈까스", desc: { ko: "", en: "" }, price: "12,500원", image: "" },
      { name: "매운돈까스", desc: { ko: "", en: "" }, price: "11,500원", image: "" },
      { name: "반반돈까스", desc: { ko: "", en: "" }, price: "12,000원", image: "" },
      { name: "저당 메밀냉 소바", desc: { ko: "", en: "" }, price: "8,000원", image: "" },
      { name: "비빔소바", desc: { ko: "", en: "" }, price: "8,500원", image: "" },
      { name: "얼큰 김치우동", desc: { ko: "", en: "" }, price: "8,500원", image: "" },
      { name: "꼬치어묵우동", desc: { ko: "", en: "" }, price: "8,000원", image: "" },
      { name: "카레우동", desc: { ko: "", en: "" }, price: "8,500원", image: "" },
      { name: "미니우동", desc: { ko: "", en: "" }, price: "3,000원", image: "" },
      { name: "새우튀김", desc: { ko: "", en: "" }, price: "3,000원", image: "" },
      { name: "치즈볼", desc: { ko: "", en: "" }, price: "3,000원", image: "" },
      { name: "공기밥", desc: { ko: "", en: "" }, price: "1,000원", image: "" },
      { name: "콜라/사이다", desc: { ko: "", en: "" }, price: "2,000원", image: "" }
    ],
    reviews: [
      { author: "Michael", text: "The King Tonkatsu is huge and delicious!", date: "2026-05-04", rating: 5, food: "옛추억의 왕돈까스" }
    ]
  },
  {
    id: 1,
    name_ko: "디저트39 익산원광대점",
    name_en: "Dessert 39",
    category: "Cafe",
    reviewCount: 131,
    hearts: 245,
    locationType: "in-campus",
    emoji: "🍰",
    coverImage: "https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로 460",
    hours: "09:00 - 22:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "크로칸 슈", desc: { ko: "바삭한 슈 안에 달콤한 크림", en: "Croquant Choux" }, price: "4,900원", image: "https://images.unsplash.com/photo-1603532648955-039310d9ed75?auto=format&fit=crop&w=200&q=80" },
      { name: "도쿄롤 (오리지널)", desc: { ko: "", en: "" }, price: "5,600원", image: "" },
      { name: "도쿄롤 (초코)", desc: { ko: "", en: "" }, price: "5,600원", image: "" },
      { name: "도쿄롤 (녹차)", desc: { ko: "", en: "" }, price: "5,600원", image: "" },
      { name: "진짜 완전 맛있는 치즈케이크", desc: { ko: "", en: "" }, price: "6,800원", image: "" },
      { name: "당근케이크", desc: { ko: "", en: "" }, price: "6,800원", image: "" },
      { name: "티라미수", desc: { ko: "", en: "" }, price: "6,500원", image: "" },
      { name: "크레이프 케이크", desc: { ko: "", en: "" }, price: "7,500원", image: "" },
      { name: "마카롱", desc: { ko: "", en: "" }, price: "3,000원", image: "" },
      { name: "아메리카노 (벤티)", desc: { ko: "대용량 아메리카노", en: "Venti Americano" }, price: "2,900원", image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=200&q=80" },
      { name: "카페라떼", desc: { ko: "", en: "" }, price: "3,900원", image: "" },
      { name: "카푸치노", desc: { ko: "", en: "" }, price: "3,900원", image: "" },
      { name: "바닐라라떼", desc: { ko: "", en: "" }, price: "4,300원", image: "" },
      { name: "카라멜마끼아또", desc: { ko: "", en: "" }, price: "4,500원", image: "" },
      { name: "딸기라떼", desc: { ko: "", en: "" }, price: "5,800원", image: "" },
      { name: "타로 밀크티", desc: { ko: "", en: "" }, price: "4,800원", image: "" },
      { name: "흑당 밀크티", desc: { ko: "", en: "" }, price: "5,200원", image: "" },
      { name: "피치 레몬 스무디", desc: { ko: "", en: "" }, price: "5,800원", image: "" }
    ],
    reviews: [
      { author: "Ahmad", text: "Best dessert cafe near campus! Really love the choux.", date: "2026-05-01", rating: 5, food: "크로칸 슈" }
    ]
  },
  {
    id: 2,
    name_ko: "다사랑치킨피자 원광대본점",
    name_en: "Dasarang Chicken & Pizza",
    category: "Restaurant",
    reviewCount: 342,
    hearts: 890,
    locationType: "out-campus",
    emoji: "🍗",
    coverImage: "https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 동서로19길 75",
    hours: "12:00 - 02:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "다사랑 양념치킨", desc: { ko: "다사랑만의 특제 양념", en: "Signature Sweet & Spicy Chicken" }, price: "19,000원", image: "https://images.unsplash.com/photo-1589302168068-964664d93cb0?auto=format&fit=crop&w=200&q=80" },
      { name: "다사랑 후라이드치킨", desc: { ko: "", en: "" }, price: "18,000원", image: "" },
      { name: "반반치킨 (후/양)", desc: { ko: "", en: "" }, price: "19,000원", image: "" },
      { name: "화살치킨", desc: { ko: "매콤한 화살치킨", en: "Spicy Arrow Chicken" }, price: "19,000원", image: "" },
      { name: "순살 양념치킨", desc: { ko: "", en: "" }, price: "20,000원", image: "" },
      { name: "순살 후라이드", desc: { ko: "", en: "" }, price: "19,000원", image: "" },
      { name: "치즈크러스트 피자", desc: { ko: "", en: "" }, price: "18,000원", image: "" },
      { name: "불고기 피자", desc: { ko: "", en: "" }, price: "17,000원", image: "" },
      { name: "포테이토 피자", desc: { ko: "", en: "" }, price: "17,000원", image: "" },
      { name: "페퍼로니 피자", desc: { ko: "", en: "" }, price: "16,000원", image: "" },
      { name: "고구마 피자", desc: { ko: "", en: "" }, price: "17,000원", image: "" },
      { name: "오븐치즈스파게티", desc: { ko: "", en: "" }, price: "7,000원", image: "" },
      { name: "새우튀김", desc: { ko: "", en: "" }, price: "8,000원", image: "" },
      { name: "감자튀김", desc: { ko: "", en: "" }, price: "6,000원", image: "" },
      { name: "생맥주 (1000cc)", desc: { ko: "", en: "" }, price: "8,000원", image: "" },
      { name: "생맥주 (2000cc)", desc: { ko: "", en: "" }, price: "15,000원", image: "" },
      { name: "콜라 (1.2L)", desc: { ko: "", en: "" }, price: "2,500원", image: "" }
    ],
    reviews: [
      { author: "John Doe", text: "Amazing chicken, the sauce is incredible! Highly recommended.", date: "2026-05-02", rating: 5, food: "다사랑 양념치킨" }
    ]
  },
  {
    id: 3,
    name_ko: "동대문엽기떡볶이 원광대점",
    name_en: "Yupdduk",
    category: "Restaurant",
    reviewCount: 250,
    hearts: 500,
    locationType: "out-campus",
    emoji: "🌶️",
    coverImage: "https://images.unsplash.com/photo-1626804475297-41609ea005eb?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 71",
    hours: "11:00 - 23:00",
    breakTime: "15:00 - 16:00",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "엽기떡볶이(착한맛)", desc: { ko: "가장 안 매운 맛", en: "Mild" }, price: "14,000원", image: "https://images.unsplash.com/photo-1580651315530-69c8e0026377?auto=format&fit=crop&w=200&q=80" },
      { name: "엽기떡볶이(초보맛)", desc: { ko: "", en: "" }, price: "14,000원", image: "" },
      { name: "엽기떡볶이(덜매운맛)", desc: { ko: "", en: "" }, price: "14,000원", image: "" },
      { name: "엽기떡볶이(오리지널)", desc: { ko: "기본 매운맛", en: "Original" }, price: "14,000원", image: "" },
      { name: "엽기떡볶이(매운맛)", desc: { ko: "아주 매운맛", en: "Spicy" }, price: "14,000원", image: "" },
      { name: "로제떡볶이", desc: { ko: "", en: "" }, price: "16,000원", image: "" },
      { name: "마라떡볶이", desc: { ko: "", en: "" }, price: "16,000원", image: "" },
      { name: "마라로제떡볶이", desc: { ko: "", en: "" }, price: "18,000원", image: "" },
      { name: "엽기오뎅", desc: { ko: "오뎅이 더 많은 버전", en: "More Fish Cakes" }, price: "14,000원", image: "" },
      { name: "엽기반반", desc: { ko: "떡과 오뎅 반반", en: "Half and Half" }, price: "14,000원", image: "" },
      { name: "엽기닭볶음탕", desc: { ko: "", en: "" }, price: "24,000원", image: "" },
      { name: "모둠튀김", desc: { ko: "", en: "" }, price: "2,000원", image: "" },
      { name: "야채튀김", desc: { ko: "", en: "" }, price: "1,000원", image: "" },
      { name: "김말이", desc: { ko: "", en: "" }, price: "2,000원", image: "" },
      { name: "만두", desc: { ko: "", en: "" }, price: "2,000원", image: "" },
      { name: "참치마요밥", desc: { ko: "", en: "" }, price: "3,500원", image: "" },
      { name: "주먹김밥", desc: { ko: "", en: "" }, price: "2,000원", image: "" },
      { name: "쿨피스", desc: { ko: "", en: "" }, price: "1,000원", image: "" },
      { name: "단무지", desc: { ko: "", en: "" }, price: "500원", image: "" },
      { name: "중국당면", desc: { ko: "", en: "" }, price: "2,500원", image: "" },
      { name: "분모자", desc: { ko: "", en: "" }, price: "2,500원", image: "" }
    ],
    reviews: [
      { author: "Sarah", text: "Too spicy for me, but my friends loved it.", date: "2026-04-15", rating: 3, food: "엽기떡볶이(오리지널)" }
    ]
  },
  {
    id: 4,
    name_ko: "얌스 원광대점",
    name_en: "Yum's",
    category: "Restaurant",
    reviewCount: 180,
    hearts: 320,
    locationType: "in-campus",
    emoji: "🍙",
    coverImage: "https://images.unsplash.com/photo-1580651315530-69c8e0026377?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로 460-1",
    hours: "10:00 - 21:00",
    breakTime: "15:30 - 17:00",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "얌스김밥", desc: { ko: "기본 야채김밥", en: "Basic Kimbap" }, price: "3,000원", image: "" },
      { name: "참치김밥", desc: { ko: "", en: "" }, price: "4,000원", image: "https://images.unsplash.com/photo-1552611052-33e04de081de?auto=format&fit=crop&w=200&q=80" },
      { name: "땡초김밥", desc: { ko: "매콤한 고추 김밥", en: "Spicy Pepper Kimbap" }, price: "4,000원", image: "" },
      { name: "돈까스김밥", desc: { ko: "", en: "" }, price: "4,500원", image: "" },
      { name: "새우튀김김밥", desc: { ko: "", en: "" }, price: "4,500원", image: "" },
      { name: "멸치김밥", desc: { ko: "", en: "" }, price: "4,000원", image: "" },
      { name: "소고기김밥", desc: { ko: "", en: "" }, price: "4,500원", image: "" },
      { name: "치즈라볶이", desc: { ko: "", en: "" }, price: "5,500원", image: "" },
      { name: "떡볶이", desc: { ko: "", en: "" }, price: "4,000원", image: "" },
      { name: "쫄면", desc: { ko: "", en: "" }, price: "6,000원", image: "" },
      { name: "우동", desc: { ko: "", en: "" }, price: "5,000원", image: "" },
      { name: "치즈돈까스", desc: { ko: "", en: "" }, price: "8,500원", image: "" },
      { name: "등심돈까스", desc: { ko: "", en: "" }, price: "7,500원", image: "" },
      { name: "고구마치즈돈까스", desc: { ko: "", en: "" }, price: "9,000원", image: "" },
      { name: "오므라이스", desc: { ko: "", en: "" }, price: "7,000원", image: "" },
      { name: "제육덮밥", desc: { ko: "", en: "" }, price: "7,500원", image: "" },
      { name: "김치볶음밥", desc: { ko: "", en: "" }, price: "6,500원", image: "" },
      { name: "새우볶음밥", desc: { ko: "", en: "" }, price: "7,000원", image: "" },
      { name: "해물볶음밥", desc: { ko: "", en: "" }, price: "7,000원", image: "" },
      { name: "라면", desc: { ko: "", en: "" }, price: "4,000원", image: "" },
      { name: "치즈라면", desc: { ko: "", en: "" }, price: "4,500원", image: "" },
      { name: "만두라면", desc: { ko: "", en: "" }, price: "4,500원", image: "" }
    ],
    reviews: [
      { author: "Ali", text: "Cheap and filling. Great for a quick lunch between classes.", date: "2026-04-20", rating: 4, food: "참치김밥" }
    ]
  },
  {
    id: 6,
    name_ko: "버거킹 익산원광대점",
    name_en: "Burger King Wonkwang Univ",
    category: "Restaurant",
    reviewCount: 450,
    hearts: 820,
    locationType: "out-campus",
    emoji: "🍔",
    coverImage: "https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로 460",
    hours: "10:00 - 22:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "와퍼", desc: { ko: "불에 직접 구운 순 쇠고기 패티", en: "Whopper" }, price: "7,100원", image: "" },
      { name: "치즈와퍼", desc: { ko: "", en: "" }, price: "7,700원", image: "" },
      { name: "불고기와퍼", desc: { ko: "", en: "" }, price: "7,100원", image: "" },
      { name: "콰트로치즈와퍼", desc: { ko: "", en: "" }, price: "7,900원", image: "" },
      { name: "통새우와퍼", desc: { ko: "", en: "" }, price: "7,900원", image: "" },
      { name: "기네스와퍼", desc: { ko: "블랙번과 기네스 바비큐 소스", en: "Guinness Whopper" }, price: "9,500원", image: "" },
      { name: "몬스터와퍼", desc: { ko: "디아블로 소스와 치킨, 비프 패티", en: "Monster Whopper" }, price: "9,300원", image: "" },
      { name: "롱치킨버거", desc: { ko: "", en: "" }, price: "4,700원", image: "" },
      { name: "프렌치프라이 (R)", desc: { ko: "", en: "" }, price: "2,100원", image: "" },
      { name: "어니언링", desc: { ko: "바삭한 양파링", en: "Onion Rings" }, price: "2,400원", image: "" },
      { name: "치즈스틱", desc: { ko: "", en: "" }, price: "1,200원", image: "" },
      { name: "21치즈스틱", desc: { ko: "21cm 롱 치즈스틱", en: "21cm Cheese Stick" }, price: "2,200원", image: "" },
      { name: "너겟킹 (8조각)", desc: { ko: "", en: "" }, price: "2,500원", image: "" },
      { name: "코카콜라 (R)", desc: { ko: "", en: "" }, price: "2,000원", image: "" },
      { name: "스프라이트 (R)", desc: { ko: "", en: "" }, price: "2,000원", image: "" },
      { name: "아메리카노", desc: { ko: "", en: "" }, price: "1,500원", image: "" }
    ],
    reviews: [{ author: "Sam", text: "Always a solid choice for a burger.", date: "2026-05-01", rating: 5, food: "와퍼" }]
  },
  {
    id: 7,
    name_ko: "맘스터치 익산원광대점",
    name_en: "Mom's Touch",
    category: "Restaurant",
    reviewCount: 380,
    hearts: 710,
    locationType: "out-campus",
    emoji: "🍔",
    coverImage: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 88",
    hours: "11:00 - 22:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "싸이버거", desc: { ko: "바삭하고 매콤한 통다리살 패티", en: "Thigh Burger" }, price: "4,600원", image: "" },
      { name: "휠렛버거", desc: { ko: "부드러운 통가슴살 패티", en: "Fillet Burger" }, price: "4,700원", image: "" },
      { name: "인크레더블 버거", desc: { ko: "계란프라이, 더블햄, 통다리살", en: "Incredible Burger" }, price: "5,700원", image: "" },
      { name: "언빌리버블 버거", desc: { ko: "통새우, 에그프라이, 통가슴살", en: "Unbelievable Burger" }, price: "5,900원", image: "" },
      { name: "딥치즈버거", desc: { ko: "진한 치즈소스가 가득", en: "Deep Cheese Burger" }, price: "5,100원", image: "" },
      { name: "화이트갈릭버거", desc: { ko: "마늘향 화이트소스와 더블햄", en: "White Garlic Burger" }, price: "5,200원", image: "" },
      { name: "불싸이버거", desc: { ko: "화끈하게 매운 싸이버거", en: "Spicy Thigh Burger" }, price: "4,800원", image: "" },
      { name: "케이준양념감자", desc: { ko: "맘스터치 시그니처 감자튀김", en: "Cajun Fries" }, price: "2,000원", image: "" },
      { name: "바삭크림치즈볼", desc: { ko: "크림치즈가 든 바삭한 볼", en: "Cream Cheese Balls" }, price: "2,000원", image: "" },
      { name: "김떡만", desc: { ko: "김말이, 떡강정, 팝콘만두", en: "Gim-Tteok-Man" }, price: "3,500원", image: "" },
      { name: "후라이드치킨 (반마리)", desc: { ko: "바삭한 치킨", en: "Fried Chicken (Half)" }, price: "9,000원", image: "" },
      { name: "맘스양념치킨 (반마리)", desc: { ko: "달콤매콤 양념", en: "Seasoned Chicken (Half)" }, price: "10,000원", image: "" },
      { name: "간장마늘치킨 (반마리)", desc: { ko: "특제 간장마늘 소스", en: "Soy Garlic Chicken (Half)" }, price: "10,000원", image: "" }
    ],
    reviews: [{ author: "Anna", text: "The chicken is so crispy and juicy!", date: "2026-04-25", rating: 5, food: "싸이버거" }]
  },
  {
    id: 8,
    name_ko: "홍콩반점0410 원광대점",
    name_en: "Hong Kong Banjum",
    category: "Restaurant",
    reviewCount: 290,
    hearts: 540,
    locationType: "out-campus",
    emoji: "🍜",
    coverImage: "https://images.unsplash.com/photo-1585032226651-759b368d7246?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 72",
    hours: "11:00 - 21:00",
    breakTime: "15:00 - 16:30",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "짜장면", desc: { ko: "달콤하고 진한 춘장 소스", en: "Black Bean Sauce Noodles" }, price: "6,500원", image: "" },
      { name: "짬뽕", desc: { ko: "얼큰하고 시원한 국물", en: "Spicy Seafood Noodle Soup" }, price: "7,800원", image: "" },
      { name: "고기짬뽕", desc: { ko: "돼지고기가 듬뿍 올라간 짬뽕", en: "Pork Jjamppong" }, price: "9,500원", image: "" },
      { name: "볶음짬뽕", desc: { ko: "매콤달콤한 볶음면", en: "Stir-fried Spicy Noodles" }, price: "8,500원", image: "" },
      { name: "탕수육(소)", desc: { ko: "쫀득한 찹쌀 탕수육", en: "Sweet and Sour Pork (Small)" }, price: "16,900원", image: "" },
      { name: "탕수육(중)", desc: { ko: "", en: "" }, price: "18,900원", image: "" },
      { name: "탕수육(대)", desc: { ko: "", en: "" }, price: "22,900원", image: "" },
      { name: "깐풍기", desc: { ko: "매콤달콤 닭고기 튀김", en: "Spicy Garlic Fried Chicken" }, price: "18,900원", image: "" },
      { name: "군만두", desc: { ko: "바삭하게 튀겨낸 군만두 한접시", en: "Fried Dumplings" }, price: "6,000원", image: "" },
      { name: "해물육교자", desc: { ko: "해물이 꽉 찬 만두", en: "Seafood Dumplings" }, price: "5,500원", image: "" },
      { name: "멘보샤", desc: { ko: "바삭한 새우 토스트", en: "Menbosha" }, price: "7,900원", image: "" },
      { name: "짜장밥", desc: { ko: "계란지단이 올라간 짜장밥", en: "Black Bean Sauce Rice" }, price: "8,500원", image: "" },
      { name: "짬뽕밥", desc: { ko: "얼큰한 짬뽕 국물과 밥", en: "Jjamppong Rice" }, price: "8,500원", image: "" }
    ],
    reviews: [{ author: "Chen", text: "Great place for affordable Chinese-Korean food.", date: "2026-04-28", rating: 4, food: "짬뽕" }]
  },
  {
    id: 9,
    name_ko: "역전우동0410 원광대점",
    name_en: "Yeokjeon Udon",
    category: "Restaurant",
    reviewCount: 150,
    hearts: 290,
    locationType: "out-campus",
    emoji: "🍜",
    coverImage: "https://images.unsplash.com/photo-1617093727343-374698b1b08d?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 60",
    hours: "11:00 - 21:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "옛날우동", desc: { ko: "진한 가쓰오부시 국물", en: "Classic Udon" }, price: "4,500원", image: "" },
      { name: "김치우동", desc: { ko: "칼칼하고 시원한 맛", en: "Kimchi Udon" }, price: "5,000원", image: "" },
      { name: "오뎅우동", desc: { ko: "커다란 오뎅이 통째로", en: "Fish Cake Udon" }, price: "5,500원", image: "" },
      { name: "새우튀김우동", desc: { ko: "바삭한 통새우 튀김이 올라간 우동", en: "Fried Shrimp Udon" }, price: "6,000원", image: "" },
      { name: "냉모밀", desc: { ko: "여름철 인기 메뉴", en: "Cold Soba" }, price: "6,000원", image: "" },
      { name: "비빔모밀", desc: { ko: "매콤새콤한 비빔모밀", en: "Spicy Mixed Soba" }, price: "6,500원", image: "" },
      { name: "돈까스덮밥", desc: { ko: "바삭한 돈까스와 특제 간장소스", en: "Tonkatsu Rice Bowl" }, price: "6,500원", image: "" },
      { name: "소불고기김치덮밥", desc: { ko: "든든한 한 끼", en: "Beef Bulgogi & Kimchi Bowl" }, price: "7,000원", image: "" },
      { name: "치킨가라아게미니덮밥", desc: { ko: "치킨가라아게가 올라간 미니 덮밥", en: "Mini Chicken Bowl" }, price: "3,500원", image: "" },
      { name: "명란미니덮밥", desc: { ko: "우동과 함께 먹기 좋은 미니덮밥", en: "Mini Pollock Roe Bowl" }, price: "3,000원", image: "" },
      { name: "돈까스(단품)", desc: { ko: "바삭한 사이드 돈까스", en: "Pork Cutlet (Side)" }, price: "5,000원", image: "" },
      { name: "새우튀김", desc: { ko: "바삭한 통새우 튀김", en: "Fried Shrimp" }, price: "2,000원", image: "" },
      { name: "치킨가라아게", desc: { ko: "일본식 닭튀김", en: "Chicken Karaage" }, price: "3,000원", image: "" }
    ],
    reviews: [{ author: "Taro", text: "Very cheap and comforting on a cold day.", date: "2026-03-12", rating: 4, food: "옛날우동" }]
  },
  {
    id: 10,
    name_ko: "두끼 원광대점",
    name_en: "Dookki Tteokbokki",
    category: "Restaurant",
    reviewCount: 420,
    hearts: 810,
    locationType: "out-campus",
    emoji: "🥘",
    coverImage: "https://images.unsplash.com/photo-1605297871329-8cbba80b1e4c?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 82",
    hours: "11:00 - 22:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "일반", desc: { ko: "무한리필 떡볶이 뷔페 (성인)", en: "Adult Buffet" }, price: "10,900원", image: "" },
      { name: "학생", desc: { ko: "무한리필 떡볶이 뷔페 (학생)", en: "Student Buffet" }, price: "9,900원", image: "" },
      { name: "소인", desc: { ko: "무한리필 떡볶이 뷔페 (7세 이하)", en: "Child Buffet" }, price: "5,900원", image: "" },
      { name: "퐁듀치즈", desc: { ko: "떡볶이를 찍어먹는 치즈 링", en: "Cheese Fondue Ring" }, price: "4,500원", image: "" },
      { name: "눈꽃치즈", desc: { ko: "떡볶이 위에 솔솔 뿌리는 눈꽃 치즈", en: "Snow Cheese" }, price: "4,500원", image: "" },
      { name: "볶음밥용치즈", desc: { ko: "마무리 볶음밥에 필수", en: "Cheese for Fried Rice" }, price: "2,500원", image: "" },
      { name: "흑미치즈볼", desc: { ko: "고소하고 달콤한 치즈볼 4개", en: "Black Rice Cheese Balls" }, price: "2,500원", image: "" },
      { name: "두끼포장(중)", desc: { ko: "마음껏 담아가는 포장 용기", en: "Take-out (Medium)" }, price: "19,000원", image: "" },
      { name: "두끼포장(대)", desc: { ko: "더 넉넉한 포장 용기", en: "Take-out (Large)" }, price: "22,000원", image: "" }
    ],
    reviews: [{ author: "Lisa", text: "Love mixing my own sauce! Fun experience.", date: "2026-05-03", rating: 5, food: "일반" }]
  },
  {
    id: 11,
    name_ko: "신전떡볶이 원광대점",
    name_en: "Sinjeon Tteokbokki",
    category: "Restaurant",
    reviewCount: 310,
    hearts: 620,
    locationType: "out-campus",
    emoji: "🌶️",
    coverImage: "https://images.unsplash.com/photo-1580651315530-69c8e0026377?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 55",
    hours: "11:00 - 22:30",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "떡볶이순한맛", desc: { ko: "카레향 국물 떡볶이", en: "Mild Tteokbokki" }, price: "3,500원", image: "" },
      { name: "떡볶이중간맛", desc: { ko: "", en: "" }, price: "3,500원", image: "" },
      { name: "떡볶이매운맛", desc: { ko: "", en: "" }, price: "3,500원", image: "" },
      { name: "치즈떡볶이", desc: { ko: "모짜렐라 치즈 듬뿍", en: "Cheese Tteokbokki" }, price: "5,500원", image: "" },
      { name: "로제떡볶이", desc: { ko: "부드럽고 매콤한 로제", en: "Rose Tteokbokki" }, price: "5,500원", image: "" },
      { name: "마라로제떡볶이", desc: { ko: "마라의 얼얼함과 로제의 부드러움", en: "Mala Rose Tteokbokki" }, price: "6,500원", image: "" },
      { name: "오뎅튀김", desc: { ko: "신전 시그니처 (5개)", en: "Fried Fish Cake" }, price: "1,700원", image: "" },
      { name: "김말이", desc: { ko: "바삭한 당면 튀김 (3개)", en: "Fried Seaweed Roll" }, price: "1,700원", image: "" },
      { name: "만두튀김", desc: { ko: "당면이 든 튀김 만두 (5개)", en: "Fried Dumpling" }, price: "1,700원", image: "" },
      { name: "잡채말이", desc: { ko: "어묵 속 잡채 (3개)", en: "Fried Glass Noodle Roll" }, price: "1,700원", image: "" },
      { name: "치즈스틱", desc: { ko: "쭉 늘어나는 치즈 (3개)", en: "Cheese Stick" }, price: "2,000원", image: "" },
      { name: "오징어튀김", desc: { ko: "통통한 오징어 튀김 (2개)", en: "Fried Squid" }, price: "2,500원", image: "" },
      { name: "신전김밥", desc: { ko: "매콤한 볶음밥 김밥", en: "Sinjeon Kimbap" }, price: "3,000원", image: "" },
      { name: "신전치즈김밥", desc: { ko: "치즈가 들어간 신전김밥", en: "Sinjeon Cheese Kimbap" }, price: "4,000원", image: "" },
      { name: "참치마요컵밥", desc: { ko: "참치와 마요네즈", en: "Tuna Mayo Rice Cup" }, price: "4,000원", image: "" },
      { name: "스팸마요컵밥", desc: { ko: "스팸과 마요네즈", en: "Spam Mayo Rice Cup" }, price: "4,000원", image: "" },
      { name: "쿨피스", desc: { ko: "매운맛 해결사", en: "Coolpis" }, price: "1,500원", image: "" }
    ],
    reviews: [{ author: "Bao", text: "Spicy but addictive. The fried fish cakes are a must.", date: "2026-04-18", rating: 5, food: "치즈떡볶이" }]
  },
  {
    id: 12,
    name_ko: "써브웨이 익산원광대점",
    name_en: "Subway",
    category: "Restaurant",
    reviewCount: 520,
    hearts: 940,
    locationType: "out-campus",
    emoji: "🥪",
    coverImage: "https://images.unsplash.com/photo-1614532650047-97d84873abdf?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로 462",
    hours: "08:00 - 22:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "이탈리안비엠티", desc: { ko: "페퍼로니, 살라미, 햄", en: "Italian B.M.T." }, price: "6,700원", image: "" },
      { name: "에그마요", desc: { ko: "부드럽고 고소한 에그마요", en: "Egg Mayo" }, price: "5,500원", image: "" },
      { name: "스테이크앤치즈", desc: { ko: "풍부한 비프 스테이크", en: "Steak & Cheese" }, price: "7,900원", image: "" },
      { name: "써브웨이클럽", desc: { ko: "터키, 햄, 베이컨", en: "Subway Club" }, price: "7,100원", image: "" },
      { name: "로스트치킨", desc: { ko: "오븐 구이 닭가슴살", en: "Roasted Chicken" }, price: "7,300원", image: "" },
      { name: "로티세리바비큐치킨", desc: { ko: "촉촉한 바비큐 치킨", en: "Rotisserie BBQ Chicken" }, price: "7,300원", image: "" },
      { name: "풀드포크바비큐", desc: { ko: "부드러운 풀드포크", en: "Pulled Pork BBQ" }, price: "7,200원", image: "" },
      { name: "스파이시이탈리안", desc: { ko: "매콤한 페퍼로니와 살라미", en: "Spicy Italian" }, price: "6,900원", image: "" },
      { name: "치킨슬라이스", desc: { ko: "닭가슴살 햄", en: "Chicken Slice" }, price: "6,500원", image: "" },
      { name: "튜나", desc: { ko: "마요네즈와 버무린 참치", en: "Tuna" }, price: "5,800원", image: "" },
      { name: "비엘티", desc: { ko: "바삭한 베이컨 듬뿍", en: "B.L.T." }, price: "6,600원", image: "" },
      { name: "미트볼", desc: { ko: "이탈리안 미트볼과 마리나라 소스", en: "Meatball" }, price: "6,500원", image: "" },
      { name: "쉬림프", desc: { ko: "통통한 새우 5마리", en: "Shrimp" }, price: "7,600원", image: "" },
      { name: "쿠키(초코칩/더블초코칩 등)", desc: { ko: "쫀득한 써브웨이 쿠키", en: "Cookie" }, price: "1,300원", image: "" },
      { name: "웨지포테이토", desc: { ko: "담백한 감자 오븐구이", en: "Wedge Potato" }, price: "2,000원", image: "" },
      { name: "탄산음료", desc: { ko: "디스펜서 탄산음료", en: "Fountain Drink" }, price: "2,000원", image: "" }
    ],
    reviews: [{ author: "John", text: "Healthy and fast. I eat here at least twice a week.", date: "2026-05-02", rating: 5, food: "이탈리안비엠티" }]
  },
  {
    id: 13,
    name_ko: "청년다방 익산원광대점",
    name_en: "Young Dabang",
    category: "Restaurant",
    reviewCount: 210,
    hearts: 480,
    locationType: "out-campus",
    emoji: "🍲",
    coverImage: "https://images.unsplash.com/photo-1544025162-8e1041935dc1?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 무왕로 856",
    hours: "11:00 - 22:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "불향차돌떡볶이", desc: { ko: "불향 가득 차돌박이와 긴 떡", en: "Beef Brisket Tteokbokki" }, price: "16,500원", image: "" },
      { name: "통큰오짱떡볶이", desc: { ko: "오징어 한마리가 통째로", en: "Fried Squid Tteokbokki" }, price: "16,500원", image: "" },
      { name: "치즈폭포순살떡볶이", desc: { ko: "순살치킨과 치즈 폭포", en: "Cheese Chicken Tteokbokki" }, price: "18,500원", image: "" },
      { name: "깻잎순대떡볶이", desc: { ko: "향긋한 깻잎과 찰순대", en: "Perilla Leaf Sundae Tteokbokki" }, price: "15,500원", image: "" },
      { name: "마라로제떡볶이", desc: { ko: "얼얼한 마라와 부드러운 로제", en: "Mala Rose Tteokbokki" }, price: "19,000원", image: "" },
      { name: "감자돌이떡볶이", desc: { ko: "감자 무스와 베이컨", en: "Potato Mousse Tteokbokki" }, price: "17,500원", image: "" },
      { name: "버터갈릭감자튀김", desc: { ko: "마약 소스 감자튀김", en: "Butter Garlic Fries" }, price: "5,500원", image: "" },
      { name: "핫버터갈릭옥수수튀김", desc: { ko: "단짠 옥수수튀김", en: "Hot Butter Garlic Corn" }, price: "5,500원", image: "" },
      { name: "다모아튀김", desc: { ko: "모둠 튀김 세트", en: "Assorted Fries" }, price: "9,500원", image: "" },
      { name: "날치알볶음밥", desc: { ko: "마무리 필수 볶음밥", en: "Flying Fish Roe Fried Rice" }, price: "3,000원", image: "" },
      { name: "청포도에이드", desc: { ko: "1리터 짐승용량 에이드", en: "Green Grape Ade" }, price: "5,500원", image: "" },
      { name: "한라봉에이드", desc: { ko: "새콤달콤 한라봉 에이드", en: "Hallabong Ade" }, price: "5,500원", image: "" },
      { name: "열대과일에이드", desc: { ko: "달달한 열대과일 에이드", en: "Tropical Fruit Ade" }, price: "5,500원", image: "" }
    ],
    reviews: [{ author: "Emily", text: "The long rice cakes are fun to cut. Very flavorful broth.", date: "2026-04-10", rating: 4, food: "불향차돌떡볶이" }]
  },
  {
    id: 14,
    name_ko: "고기싸롱 원광대점",
    name_en: "Gogi Salon",
    category: "Restaurant",
    reviewCount: 400,
    hearts: 760,
    locationType: "out-campus",
    emoji: "🥓",
    coverImage: "https://images.unsplash.com/photo-1544365558-35aa4afcf11f?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 91",
    hours: "11:30 - 23:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "무한리필런치", desc: { ko: "평일 15시 이전", en: "Lunch Buffet" }, price: "17,500원", image: "" },
      { name: "무한리필디너", desc: { ko: "평일 저녁, 주말 및 공휴일", en: "Dinner/Weekend Buffet" }, price: "18,500원", image: "" },
      { name: "미취학아동", desc: { ko: "36개월~7세", en: "Preschooler" }, price: "7,000원", image: "" },
      { name: "초등학생", desc: { ko: "8세~10세", en: "Young Child" }, price: "10,000원", image: "" },
      { name: "물냉면", desc: { ko: "살얼음 동동 물냉면", en: "Cold Noodle Soup" }, price: "6,000원", image: "" },
      { name: "비빔냉면", desc: { ko: "매콤달콤 비빔냉면", en: "Spicy Cold Noodles" }, price: "6,000원", image: "" },
      { name: "된장찌개", desc: { ko: "고기 먹을 때 필수", en: "Soybean Paste Stew" }, price: "4,000원", image: "" },
      { name: "음료수", desc: { ko: "콜라, 사이다 등", en: "Soft Drinks" }, price: "2,000원", image: "" }
    ],
    reviews: [{ author: "Dan", text: "Great value for the amount of meat you get. Always crowded.", date: "2026-04-22", rating: 4, food: "무한리필디너" }]
  },
  {
    id: 15,
    name_ko: "짚신매운갈비찜 원광대점",
    name_en: "Jipsin Spicy Ribs",
    category: "Restaurant",
    reviewCount: 180,
    hearts: 310,
    locationType: "out-campus",
    emoji: "🍖",
    coverImage: "https://images.unsplash.com/photo-1544025162-8e1041935dc1?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 70",
    hours: "11:30 - 24:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "돼지갈비찜(매운맛)", desc: { ko: "10%~100% 맵기 선택", en: "Spicy Pork Ribs" }, price: "15,000원", image: "" },
      { name: "돼지갈비찜(간장맛)", desc: { ko: "아이도 먹을 수 있는 간장맛", en: "Soy Sauce Pork Ribs" }, price: "15,000원", image: "" },
      { name: "소갈비찜(매운맛)", desc: { ko: "부드러운 소갈비", en: "Spicy Beef Ribs" }, price: "20,000원", image: "" },
      { name: "소갈비찜(간장맛)", desc: { ko: "간장 양념 소갈비찜", en: "Soy Sauce Beef Ribs" }, price: "20,000원", image: "" },
      { name: "짚신국밥", desc: { ko: "든든한 점심 특선", en: "Jipsin Rice Soup" }, price: "8,000원", image: "" },
      { name: "참치마요주먹밥", desc: { ko: "갈비찜과 찰떡궁합", en: "Tuna Mayo Rice Balls" }, price: "4,500원", image: "" },
      { name: "날치알주먹밥", desc: { ko: "톡톡 터지는 날치알", en: "Flying Fish Roe Rice Balls" }, price: "4,000원", image: "" },
      { name: "주먹밥", desc: { ko: "기본 주먹밥", en: "Rice Balls" }, price: "3,000원", image: "" },
      { name: "치즈계란찜", desc: { ko: "모짜렐라 치즈가 가득", en: "Cheese Steamed Egg" }, price: "5,000원", image: "" },
      { name: "계란찜", desc: { ko: "부드러운 계란찜", en: "Steamed Egg" }, price: "4,000원", image: "" },
      { name: "고추만두", desc: { ko: "바삭한 고추모양 만두", en: "Fried Pepper Dumplings" }, price: "6,000원", image: "" },
      { name: "당면사리", desc: { ko: "국물을 빨아들인 당면", en: "Glass Noodles" }, price: "2,000원", image: "" },
      { name: "떡사리", desc: { ko: "쫄깃한 밀떡 추가", en: "Rice Cakes" }, price: "2,000원", image: "" },
      { name: "볶음밥", desc: { ko: "마무리 볶음밥", en: "Fried Rice" }, price: "3,000원", image: "" }
    ],
    reviews: [{ author: "Kim", text: "I ordered 30% spicy and it was perfect.", date: "2026-03-30", rating: 5, food: "돼지갈비찜(매운맛)" }]
  },
  
  // --- 카페 카테고리 ---
  {
    id: 16,
    name_ko: "스타벅스 익산원광대점",
    name_en: "Starbucks Wonkwang Univ",
    category: "Cafe",
    reviewCount: 950,
    hearts: 1500,
    locationType: "out-campus",
    emoji: "☕",
    coverImage: "https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로 460",
    hours: "07:30 - 22:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "아메리카노", desc: { ko: "스타벅스 대표 에스프레소", en: "Americano" }, price: "4,500원", image: "" },
      { name: "카페라떼", desc: { ko: "풍부한 에스프레소와 스팀 밀크", en: "Cafe Latte" }, price: "5,000원", image: "" },
      { name: "카라멜마키아또", desc: { ko: "달콤한 카라멜 드리즐", en: "Caramel Macchiato" }, price: "5,900원", image: "" },
      { name: "돌체라떼", desc: { ko: "연유가 들어간 부드러운 라떼", en: "Dolce Latte" }, price: "5,900원", image: "" },
      { name: "바닐라크림콜드브루", desc: { ko: "깔끔한 콜드브루와 달콤한 바닐라 크림", en: "Vanilla Cream Cold Brew" }, price: "5,800원", image: "" },
      { name: "자몽허니블랙티", desc: { ko: "새콤달콤한 자몽과 홍차의 조화", en: "Grapefruit Honey Black Tea" }, price: "5,700원", image: "" },
      { name: "쿨라임피지오", desc: { ko: "그린 빈 추출액이 들어간 청량한 음료", en: "Cool Lime Starbucks Fizzio" }, price: "5,900원", image: "" },
      { name: "자바칩프라푸치노", desc: { ko: "초콜릿 칩이 씹히는 달콤한 프라푸치노", en: "Java Chip Frappuccino" }, price: "6,300원", image: "" },
      { name: "말차프라푸치노", desc: { ko: "제주산 말차로 만든 프라푸치노", en: "Jeju Matcha Frappuccino" }, price: "6,300원", image: "" },
      { name: "피치스트로베리블렌디드", desc: { ko: "상큼한 복숭아와 딸기 블렌디드", en: "Peach Strawberry Blended" }, price: "6,500원", image: "" },
      { name: "유자민트티", desc: { ko: "달콤한 유자와 상쾌한 민트티", en: "Yuja Mint Tea" }, price: "5,900원", image: "" },
      { name: "부드러운 생크림카스텔라", desc: { ko: "스타벅스 인기 디저트 1위", en: "Fresh Cream Castella" }, price: "4,500원", image: "" },
      { name: "마스카포네 티라미수 케이크", desc: { ko: "진한 에스프레소 시럽과 크림치즈", en: "Mascarpone Tiramisu Cake" }, price: "5,900원", image: "" },
      { name: "블루베리쿠키치즈케이크", desc: { ko: "바삭한 쿠키 타르트와 진한 치즈", en: "Blueberry Cookie Cheese Cake" }, price: "6,900원", image: "" },
      { name: "바비큐치킨치즈치아바타", desc: { ko: "바비큐 소스 치킨이 들어간 샌드위치", en: "BBQ Chicken Cheese Ciabatta" }, price: "5,800원", image: "" },
      { name: "하트파이", desc: { ko: "바삭하고 달콤한 파이", en: "Heart Pie" }, price: "3,200원", image: "" }
    ],
    reviews: [{ author: "Alice", text: "Good place to study, but it gets busy.", date: "2026-05-04", rating: 4, food: "아메리카노" }]
  },
  {
    id: 17,
    name_ko: "메가MGC커피 원광대점",
    name_en: "Mega Coffee",
    category: "Cafe",
    reviewCount: 520,
    hearts: 890,
    locationType: "out-campus",
    emoji: "☕",
    coverImage: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 75",
    hours: "08:00 - 23:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "아메리카노", desc: { ko: "가성비 좋은 대용량 아메리카노", en: "Americano" }, price: "1,500원", image: "" },
      { name: "메가리카노", desc: { ko: "1리터 초대용량", en: "Mega Americano" }, price: "3,000원", image: "" },
      { name: "카페라떼", desc: { ko: "고소한 라떼", en: "Cafe Latte" }, price: "2,900원", image: "" },
      { name: "큐브라떼", desc: { ko: "에스프레소 얼음 큐브가 들어간 라떼", en: "Cube Latte" }, price: "4,200원", image: "" },
      { name: "헤이즐넛라떼", desc: { ko: "헤이즐넛 시럽이 듬뿍", en: "Hazelnut Latte" }, price: "3,400원", image: "" },
      { name: "딸기라떼", desc: { ko: "생딸기 과육이 가득", en: "Strawberry Latte" }, price: "3,700원", image: "" },
      { name: "퐁크러쉬플레인", desc: { ko: "죠리퐁 쉐이크 오리지널", en: "Jolly Pong Crush Plain" }, price: "3,900원", image: "" },
      { name: "퐁크러쉬딸기", desc: { ko: "딸기맛 죠리퐁 쉐이크", en: "Jolly Pong Crush Strawberry" }, price: "3,900원", image: "" },
      { name: "퐁크러쉬바나나", desc: { ko: "바나나맛 죠리퐁 쉐이크", en: "Jolly Pong Crush Banana" }, price: "3,900원", image: "" },
      { name: "쿠키프라페", desc: { ko: "오레오 쿠키 크런치 프라페", en: "Cookie Frappe" }, price: "3,900원", image: "" },
      { name: "스트로베리치즈홀릭", desc: { ko: "치즈케이크가 통째로 올라간 딸기 스무디", en: "Strawberry Cheese Holic" }, price: "4,500원", image: "" },
      { name: "유니콘프라페", desc: { ko: "알록달록 예쁜 솜사탕맛 프라페", en: "Unicorn Frappe" }, price: "4,800원", image: "" },
      { name: "체리콕", desc: { ko: "달콤 상큼한 체리 콜라", en: "Cherry Coke" }, price: "3,300원", image: "" },
      { name: "감자빵", desc: { ko: "강원도 춘천 명물 쫀득한 감자빵", en: "Potato Bread" }, price: "3,500원", image: "" },
      { name: "크로플", desc: { ko: "겉바속촉 크루아상 와플", en: "Croffle" }, price: "2,500원", image: "" }
    ],
    reviews: [{ author: "David", text: "Huge coffee for a very low price. Perfect for students.", date: "2026-05-01", rating: 5, food: "메가리카노" }]
  },
  {
    id: 18,
    name_ko: "컴포즈커피 익산원광대점",
    name_en: "Compose Coffee",
    category: "Cafe",
    reviewCount: 310,
    hearts: 620,
    locationType: "out-campus",
    emoji: "☕",
    coverImage: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 66",
    hours: "08:00 - 22:30",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "아메리카노", desc: { ko: "가성비 스페셜티 블렌딩", en: "Americano" }, price: "1,500원", image: "" },
      { name: "카페라떼", desc: { ko: "고소한 우유와 에스프레소", en: "Cafe Latte" }, price: "2,900원", image: "" },
      { name: "돌체라떼", desc: { ko: "달달한 연유가 듬뿍", en: "Dolce Latte" }, price: "3,500원", image: "" },
      { name: "아인슈페너", desc: { ko: "부드러운 크림이 올라간 커피", en: "Einspanner" }, price: "3,900원", image: "" },
      { name: "바닐라라떼", desc: { ko: "향긋한 바닐라", en: "Vanilla Latte" }, price: "3,300원", image: "" },
      { name: "상하목장밀크쉐이크", desc: { ko: "상하목장 원유로 만든 프리미엄 쉐이크", en: "Milk Shake" }, price: "4,200원", image: "" },
      { name: "팥절미밀크쉐이크", desc: { ko: "인절미와 팥이 들어간 고소한 쉐이크", en: "Red Bean Injeolmi Shake" }, price: "4,200원", image: "" },
      { name: "딸기스무디", desc: { ko: "상큼 달콤한 딸기 스무디", en: "Strawberry Smoothie" }, price: "3,800원", image: "" },
      { name: "초코오레오프라페", desc: { ko: "초코와 오레오 쿠키", en: "Choco Oreo Frappe" }, price: "3,900원", image: "" },
      { name: "자몽에이드", desc: { ko: "상큼한 자몽", en: "Grapefruit Ade" }, price: "3,500원", image: "" },
      { name: "유자티", desc: { ko: "따뜻한 유자차", en: "Yuja Tea" }, price: "3,500원", image: "" },
      { name: "크로플", desc: { ko: "버터 풍미 가득", en: "Croffle" }, price: "2,500원", image: "" },
      { name: "사과생크림와플", desc: { ko: "옛날 길거리 와플 맛", en: "Apple Cream Waffle" }, price: "3,000원", image: "" }
    ],
    reviews: [{ author: "Jane", text: "Unbeatable price.", date: "2026-04-20", rating: 5, food: "아메리카노" }]
  },
  {
    id: 19,
    name_ko: "빽다방 익산원광대점",
    name_en: "Paik's Coffee",
    category: "Cafe",
    reviewCount: 410,
    hearts: 700,
    locationType: "out-campus",
    emoji: "🧋",
    coverImage: "https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 71",
    hours: "08:30 - 22:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "앗메리카노", desc: { ko: "각얼음/간얼음 선택 가능", en: "Americano" }, price: "2,000원", image: "" },
      { name: "원조커피", desc: { ko: "백종원 대표 추천 다방 커피", en: "Original Mixed Coffee" }, price: "2,500원", image: "" },
      { name: "달달연유라떼", desc: { ko: "베트남 연유가 들어간 라떼", en: "Sweet Condensed Milk Latte" }, price: "3,700원", image: "" },
      { name: "빽스라떼", desc: { ko: "고소한 빽다방 라떼", en: "Paik's Latte" }, price: "3,000원", image: "" },
      { name: "바닐라라떼", desc: { ko: "바닐라 파우더 라떼", en: "Vanilla Latte" }, price: "3,700원", image: "" },
      { name: "완전초코", desc: { ko: "아주 진한 리얼 초콜릿 음료", en: "Deep Chocolate" }, price: "3,500원", image: "" },
      { name: "피스타치오빽스치노", desc: { ko: "견과류의 고소함과 달콤함 (소프트 추가)", en: "Pistachio Paik'sccino" }, price: "4,500원", image: "" },
      { name: "딸기빽스치노", desc: { ko: "상큼한 딸기 듬뿍", en: "Strawberry Paik'sccino" }, price: "4,000원", image: "" },
      { name: "녹차빽스치노", desc: { ko: "진한 녹차맛 프라페", en: "Green Tea Paik'sccino" }, price: "4,000원", image: "" },
      { name: "노말한소프트", desc: { ko: "빽다방 기본 소프트 아이스크림", en: "Soft Ice Cream" }, price: "2,000원", image: "" },
      { name: "사라다빵", desc: { ko: "감자 샐러드가 꽉 찬 추억의 빵", en: "Potato Salad Bread" }, price: "3,000원", image: "" },
      { name: "소세지빵", desc: { ko: "치즈와 옥수수 톡톡 터지는 소세지 빵", en: "Sausage Bread" }, price: "3,500원", image: "" },
      { name: "크리미슈", desc: { ko: "부드럽고 시원한 크림슈", en: "Creamy Choux" }, price: "2,000원", image: "" },
      { name: "공공치빵", desc: { ko: "대파 크림치즈가 들어간 빵", en: "Green Onion Cream Cheese Bread" }, price: "3,000원", image: "" }
    ],
    reviews: [{ author: "Mark", text: "The sweet coffee gives me a sugar rush for studying.", date: "2026-04-18", rating: 4, food: "원조커피" }]
  },
  {
    id: 20,
    name_ko: "이디야커피 익산원광대점",
    name_en: "Ediya Coffee",
    category: "Cafe",
    reviewCount: 250,
    hearts: 480,
    locationType: "out-campus",
    emoji: "☕",
    coverImage: "https://images.unsplash.com/photo-1495474472207-464a4ad54e50?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로 458",
    hours: "09:00 - 23:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "아메리카노", desc: { ko: "진하고 부드러운 이디야 아메리카노", en: "Americano" }, price: "3,200원", image: "" },
      { name: "카페라떼", desc: { ko: "에스프레소와 스팀 밀크", en: "Cafe Latte" }, price: "4,200원", image: "" },
      { name: "바닐라라떼", desc: { ko: "달콤한 바닐라 향", en: "Vanilla Latte" }, price: "4,500원", image: "" },
      { name: "토피넛라떼", desc: { ko: "이디야 부동의 1위 시그니처, 달콤 고소한 견과류 맛", en: "Toffee Nut Latte" }, price: "4,200원", image: "" },
      { name: "고구마라떼", desc: { ko: "달콤하고 부드러운 고구마 페이스트", en: "Sweet Potato Latte" }, price: "4,200원", image: "" },
      { name: "녹차라떼", desc: { ko: "진한 녹차의 풍미", en: "Green Tea Latte" }, price: "3,900원", image: "" },
      { name: "꿀복숭아플랫치노", desc: { ko: "시원하고 상큼한 복숭아 슬러시", en: "Honey Peach Flatccino" }, price: "3,900원", image: "" },
      { name: "초코쿠키쉐이크", desc: { ko: "바삭한 초코쿠키 크런치", en: "Choco Cookie Shake" }, price: "4,900원", image: "" },
      { name: "딸기쉐이크", desc: { ko: "부드럽고 달콤한 딸기 쉐이크", en: "Strawberry Shake" }, price: "4,900원", image: "" },
      { name: "복숭아아이스티", desc: { ko: "여름철 갈증 해소에 최고 (EX사이즈 추천)", en: "Peach Iced Tea" }, price: "2,900원", image: "" },
      { name: "허니카라멜브레드", desc: { ko: "생크림과 카라멜 소스가 듬뿍 뿌려진 허니브레드", en: "Honey Caramel Bread" }, price: "5,200원", image: "" },
      { name: "플레인베이글", desc: { ko: "크림치즈 발라 먹는 담백한 베이글", en: "Plain Bagel" }, price: "2,500원", image: "" },
      { name: "프레첼", desc: { ko: "짭짤하고 고소한 프레첼", en: "Pretzel" }, price: "2,800원", image: "" }
    ],
    reviews: [{ author: "Sonia", text: "Toffee nut latte is the best here.", date: "2026-03-25", rating: 5, food: "토피넛라떼" }]
  },
  {
    id: 21,
    name_ko: "투썸플레이스 익산원대점",
    name_en: "A Twosome Place",
    category: "Cafe",
    reviewCount: 560,
    hearts: 1100,
    locationType: "out-campus",
    emoji: "🍰",
    coverImage: "https://images.unsplash.com/photo-1551024601-bec78aea704b?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로 462",
    hours: "09:00 - 24:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "아메리카노", desc: { ko: "원두 선택 가능 (블랙그라운드/아로마노트)", en: "Americano" }, price: "4,500원", image: "" },
      { name: "카페라떼", desc: { ko: "고소하고 진한 라떼", en: "Cafe Latte" }, price: "5,000원", image: "" },
      { name: "스페니쉬연유라떼", desc: { ko: "달콤한 연유가 들어간 스페인식 라떼", en: "Spanish Condensed Milk Latte" }, price: "5,800원", image: "" },
      { name: "신촌커피", desc: { ko: "바닐라빈이 들어간 시그니처 믹스 라떼", en: "Sinchon Coffee" }, price: "6,100원", image: "" },
      { name: "롱블랙", desc: { ko: "더 깊고 진한 에스프레소의 풍미", en: "Long Black" }, price: "4,500원", image: "" },
      { name: "스트로베리피치프라페", desc: { ko: "상큼한 딸기와 복숭아의 만남", en: "Strawberry Peach Frappe" }, price: "6,100원", image: "" },
      { name: "로얄밀크티쉐이크", desc: { ko: "홍차 아이스크림이 올라간 쉐이크", en: "Royal Milk Tea Shake" }, price: "6,300원", image: "" },
      { name: "아이스박스", desc: { ko: "마스카포네 크림과 오레오 쿠키가 층층이 쌓인 케이크", en: "Ice Box Cake" }, price: "6,500원", image: "" },
      { name: "스트로베리초콜릿생크림", desc: { ko: "딸기가 가득 올라간 초코 케이크 (조각)", en: "Strawberry Choco Cake" }, price: "6,700원", image: "" },
      { name: "마스카포네티라미수", desc: { ko: "부드러운 이탈리안 티라미수", en: "Mascarpone Tiramisu" }, price: "6,500원", image: "" },
      { name: "뉴욕치즈케이크", desc: { ko: "진하고 크리미한 정통 치즈 케이크", en: "New York Cheese Cake" }, price: "5,900원", image: "" },
      { name: "레드벨벳", desc: { ko: "크림치즈 프로스팅이 올라간 레드벨벳 케이크", en: "Red Velvet Cake" }, price: "6,500원", image: "" },
      { name: "마카롱", desc: { ko: "바닐라/초코/산딸기 등", en: "Macaron" }, price: "2,700원", image: "" }
    ],
    reviews: [{ author: "Yuri", text: "Desserts are amazing. The Ice Box is a must-try.", date: "2026-05-02", rating: 5, food: "아이스박스" }]
  },
  {
    id: 22,
    name_ko: "아마스빈 익산원광대점",
    name_en: "Amasvin Bubble Tea",
    category: "Cafe",
    reviewCount: 320,
    hearts: 680,
    locationType: "out-campus",
    emoji: "🧋",
    coverImage: "https://images.unsplash.com/photo-1558855567-1a3af4b0cbab?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 76",
    hours: "10:00 - 22:30",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "타로밀크티", desc: { ko: "아마스빈 부동의 1위 메뉴 (펄 포함)", en: "Taro Milk Tea" }, price: "3,900원", image: "" },
      { name: "얼그레이밀크티", desc: { ko: "진한 얼그레이 홍차 베이스", en: "Earl Grey Milk Tea" }, price: "3,700원", image: "" },
      { name: "루이보스밀크티", desc: { ko: "카페인 없는 깔끔한 밀크티", en: "Rooibos Milk Tea" }, price: "3,700원", image: "" },
      { name: "아쌈밀크티", desc: { ko: "가장 클래식한 블랙 밀크티", en: "Assam Milk Tea" }, price: "3,700원", image: "" },
      { name: "코코넛밀크티", desc: { ko: "코코넛의 고소하고 달콤한 맛", en: "Coconut Milk Tea" }, price: "3,900원", image: "" },
      { name: "하동사과스무디", desc: { ko: "국내산 사과로 만든 상큼 스무디", en: "Hadong Apple Smoothie" }, price: "3,900원", image: "" },
      { name: "애플망고스무디", desc: { ko: "달콤한 애플망고 스무디", en: "Apple Mango Smoothie" }, price: "4,000원", image: "" },
      { name: "초코오레오쉐이크", desc: { ko: "초코와 오레오 쿠키 크런치", en: "Choco Oreo Shake" }, price: "4,200원", image: "" },
      { name: "녹차오레오쉐이크", desc: { ko: "녹차와 오레오의 만남", en: "Green Tea Oreo Shake" }, price: "4,200원", image: "" },
      { name: "사하라", desc: { ko: "우유 베이스의 딸기+파인애플+오렌지 블렌딩", en: "Sahara" }, price: "4,000원", image: "" },
      { name: "오아시스", desc: { ko: "키위+청포도+사과 과일 블렌딩", en: "Oasis" }, price: "4,000원", image: "" },
      { name: "레몬머스캣", desc: { ko: "청포도와 레몬의 청량한 조화", en: "Lemon Muscat" }, price: "3,800원", image: "" }
    ],
    reviews: [{ author: "Mina", text: "Chewy pearls and not too sweet.", date: "2026-04-12", rating: 4, food: "타로밀크티" }]
  },
  {
    id: 23,
    name_ko: "공차 익산원광대점",
    name_en: "Gong Cha",
    category: "Cafe",
    reviewCount: 430,
    hearts: 850,
    locationType: "out-campus",
    emoji: "🧋",
    coverImage: "https://images.unsplash.com/photo-1596766472251-40b4352fb38e?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로54길 80",
    hours: "10:00 - 22:30",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "블랙밀크티+펄", desc: { ko: "공차 베스트셀러", en: "Black Milk Tea with Pearl" }, price: "4,700원", image: "" },
      { name: "타로밀크티+펄", desc: { ko: "달콤하고 고소한 타로", en: "Taro Milk Tea with Pearl" }, price: "4,700원", image: "" },
      { name: "우롱밀크티", desc: { ko: "고소하고 깔끔한 우롱차", en: "Oolong Milk Tea" }, price: "4,500원", image: "" },
      { name: "얼그레이밀크티", desc: { ko: "향긋한 얼그레이", en: "Earl Grey Milk Tea" }, price: "4,500원", image: "" },
      { name: "제주그린밀크티+펄", desc: { ko: "쌉싸름한 제주산 녹차", en: "Jeju Green Milk Tea with Pearl" }, price: "5,100원", image: "" },
      { name: "브라운슈가쥬얼리밀크티", desc: { ko: "흑당 시럽과 쫀득한 쥬얼리 펄", en: "Brown Sugar Jewelry Milk Tea" }, price: "5,500원", image: "" },
      { name: "딸기쥬얼리밀크티", desc: { ko: "딸기 시럽과 딸기 펄", en: "Strawberry Jewelry Milk Tea" }, price: "5,300원", image: "" },
      { name: "망고스무디", desc: { ko: "달콤한 망고 스무디", en: "Mango Smoothie" }, price: "5,500원", image: "" },
      { name: "초코쿠앤크스무디", desc: { ko: "초코와 오레오 쉐이크", en: "Choco Cookies & Cream Smoothie" }, price: "5,300원", image: "" },
      { name: "망고요구르트+화이트펄", desc: { ko: "상큼한 망고 요구르트와 꼬들한 화이트펄", en: "Mango Yogurt with White Pearl" }, price: "5,400원", image: "" },
      { name: "청포도그린티+알로에", desc: { ko: "청량한 청포도 에이드 느낌", en: "Green Grape Green Tea with Aloe" }, price: "5,200원", image: "" },
      { name: "자몽큐앤에이", desc: { ko: "자몽 과육과 알로에 젤리", en: "Grapefruit Q&A" }, price: "5,400원", image: "" }
    ],
    reviews: [{ author: "Kevin", text: "The sugar level customization is great.", date: "2026-04-28", rating: 5, food: "블랙밀크티+펄" }]
  },
  {
    id: 24,
    name_ko: "파스쿠찌 익산원광대점",
    name_en: "Pascucci",
    category: "Cafe",
    reviewCount: 150,
    hearts: 300,
    locationType: "out-campus",
    emoji: "☕",
    coverImage: "https://images.unsplash.com/photo-1511920170033-f8396924c648?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 익산대로 461",
    hours: "09:00 - 23:00",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "아메리카노", desc: { ko: "정통 이탈리안 에스프레소 베이스", en: "Americano" }, price: "4,500원", image: "" },
      { name: "카페라떼", desc: { ko: "우유 폼이 부드러운 라떼", en: "Cafe Latte" }, price: "5,000원", image: "" },
      { name: "카라멜마끼아또", desc: { ko: "달콤한 카라멜 소스", en: "Caramel Macchiato" }, price: "5,800원", image: "" },
      { name: "바닐라라떼마끼아또", desc: { ko: "바닐라 향 가득한 마끼아또", en: "Vanilla Latte Macchiato" }, price: "5,800원", image: "" },
      { name: "헤이즐넛카푸치노", desc: { ko: "풍부한 거품과 헤이즐넛 향", en: "Hazelnut Cappuccino" }, price: "5,500원", image: "" },
      { name: "모카브라우니그라니따", desc: { ko: "브라우니가 통째로 올라간 쉐이크", en: "Mocha Brownie Granita" }, price: "6,800원", image: "" },
      { name: "스트로베리젤라또그라니따", desc: { ko: "젤라또 아이스크림 딸기 쉐이크", en: "Strawberry Gelato Granita" }, price: "6,900원", image: "" },
      { name: "플레인요거트그라니따", desc: { ko: "새콤달콤 플레인 요거트 스무디", en: "Plain Yogurt Granita" }, price: "6,300원", image: "" },
      { name: "젤라또 (2스쿱)", desc: { ko: "이탈리아 정통 쫀득한 아이스크림", en: "Gelato (2 Scoops)" }, price: "4,500원", image: "" },
      { name: "클래식 파니니", desc: { ko: "햄과 치즈가 들어간 따뜻한 샌드위치", en: "Classic Panini" }, price: "6,500원", image: "" },
      { name: "티라미수", desc: { ko: "커피와 잘 어울리는 촉촉한 케이크", en: "Tiramisu" }, price: "6,000원", image: "" }
    ],
    reviews: [{ author: "Elena", text: "A bit pricey but the gelato is good.", date: "2026-03-05", rating: 4, food: "젤라또" }]
  },
  {
    id: 25,
    name_ko: "설빙 익산원광대점",
    name_en: "Sulbing",
    category: "Cafe",
    reviewCount: 480,
    hearts: 920,
    locationType: "out-campus",
    emoji: "🍧",
    coverImage: "https://images.unsplash.com/photo-1558231575-cf0fc964b07e?auto=format&fit=crop&w=600&q=80",
    address: "전북 익산시 무왕로 855",
    hours: "11:30 - 22:30",
    breakTime: "",
    mapNaver: "https://map.naver.com",
    mapGoogle: "https://maps.google.com",
    menu: [
      { name: "인절미설빙", desc: { ko: "설빙의 대표 메뉴, 고소한 콩가루", en: "Injeolmi Bingsu" }, price: "8,900원", image: "" },
      { name: "팥인절미설빙", desc: { ko: "달콤한 팥이 추가된 인절미 빙수", en: "Red Bean Injeolmi Bingsu" }, price: "9,900원", image: "" },
      { name: "초코브라우니설빙", desc: { ko: "달콤한 초코 큐브와 브라우니", en: "Choco Brownie Bingsu" }, price: "11,900원", image: "" },
      { name: "치즈설빙", desc: { ko: "큐브 치즈케이크가 듬뿍", en: "Cheese Bingsu" }, price: "10,900원", image: "" },
      { name: "애플망고치즈설빙", desc: { ko: "상큼한 망고와 치즈 큐브", en: "Apple Mango Cheese Bingsu" }, price: "12,900원", image: "" },
      { name: "리얼그린티설빙", desc: { ko: "진한 녹차 아이스크림과 떡", en: "Real Green Tea Bingsu" }, price: "10,500원", image: "" },
      { name: "오레오초코몬스터설빙", desc: { ko: "오레오 쿠키 가득", en: "Oreo Choco Monster Bingsu" }, price: "11,900원", image: "" },
      { name: "인절미토스트", desc: { ko: "바삭한 식빵 속 쫄깃한 인절미", en: "Injeolmi Toast" }, price: "4,800원", image: "" },
      { name: "쌍쌍치즈가래떡", desc: { ko: "치즈가 들어간 구운 가래떡", en: "Cheese Rice Cake" }, price: "4,000원", image: "" },
      { name: "꿀호떡", desc: { ko: "겨울철 인기 간식", en: "Honey Hotteok" }, price: "1,800원", image: "" },
      { name: "미니붕어빵", desc: { ko: "팥/슈크림 선택", en: "Mini Taiyaki" }, price: "2,500원", image: "" },
      { name: "딥초코츄러스", desc: { ko: "초코 시럽 듬뿍 츄러스", en: "Deep Choco Churros" }, price: "2,900원", image: "" }
    ],
    reviews: [{ author: "Lucas", text: "Perfect for a hot day! Mango bingsu is delicious.", date: "2026-05-08", rating: 5, food: "애플망고치즈설빙" }]
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { mockRestaurants, mockScripts };
}

// app.js

const translations = {
  ko: {
    top3_title: "이번 주 인기 TOP 3",
    categories_title: "카테고리",
    cat_all: "전체",
    cat_restaurant: "식당",
    cat_cafe: "카페",
    cat_others: "기타",
    modal_title: "상황별 대화 스크립트",
    modal_desc: "실제 주문과 소통에 유용한 표현들입니다.",
    menu_title: "메뉴",
    reviews_title: "리뷰",
    post_review: "리뷰 남기기",
    open_scripts: "🗣️ 대화 스크립트 열기",
    back_to_list: "⬅️ 목록으로",
    map_link: "📍 지도 보기",
    theme_light: "일반",
    theme_dark: "다크",
    theme_truetone: "트루톤",
    rating_label: "별점 (0~5)",
    food_label: "먹은 메뉴",
    review_placeholder: "10단어 이상 솔직한 리뷰를 남겨주세요.",
    loc_all: "전체 위치",
    loc_in_campus: "교내 식당",
    loc_out_campus: "교외 식당"
  },
  en: {
    top3_title: "This Week's Top 3",
    categories_title: "Categories",
    cat_all: "All",
    cat_restaurant: "Restaurant",
    cat_cafe: "Cafe",
    cat_others: "Others",
    modal_title: "Situation-based Scripts",
    modal_desc: "Use these phrases to order and communicate easily.",
    menu_title: "Menu",
    reviews_title: "Reviews",
    post_review: "Post Review",
    open_scripts: "🗣️ Open Conversation Scripts",
    back_to_list: "⬅️ Back to List",
    map_link: "📍 View Map",
    theme_light: "Light",
    theme_dark: "Dark",
    theme_truetone: "True Tone",
    rating_label: "Rating (0~5)",
    food_label: "Food Eaten",
    review_placeholder: "Write an honest review (min 10 words).",
    loc_all: "All Locations",
    loc_in_campus: "In-campus",
    loc_out_campus: "Out-campus"
  },
  uz: {
    top3_title: "Bu haftaning Top 3 tasi",
    categories_title: "Kategoriyalar",
    cat_all: "Barchasi",
    cat_restaurant: "Restoran",
    cat_cafe: "Kafe",
    cat_others: "Boshqalar",
    modal_title: "Vaziyatli skriptlar",
    modal_desc: "Oson buyurtma berish va muloqot qilish uchun ushbu iboralardan foydalaning.",
    menu_title: "Menyu",
    reviews_title: "Sharhlar",
    post_review: "Sharh yozish",
    open_scripts: "🗣️ Muloqot skriptlarini oching",
    back_to_list: "⬅️ Ro'yxatga qaytish",
    map_link: "📍 Xaritani ko'rish",
    theme_light: "Oddiy",
    theme_dark: "Qorong'i",
    theme_truetone: "Haqiqiy ohang",
    rating_label: "Baho (0~5)",
    food_label: "Yegan ovqati",
    review_placeholder: "Rostgo'y sharh qoldiring (kamida 10 so'z).",
    loc_all: "Barcha joylar",
    loc_in_campus: "Kampus ichida",
    loc_out_campus: "Kampus tashqarisida"
  },
  ur: {
    top3_title: "اس ہفتے کے ٹاپ 3",
    categories_title: "اقسام",
    cat_all: "سب",
    cat_restaurant: "ریستوراں",
    cat_cafe: "کیفے",
    cat_others: "دیگر",
    modal_title: "صورتحال پر مبنی اسکرپٹس",
    modal_desc: "آسانی سے آرڈر کرنے اور بات چیت کرنے کے لیے ان فقروں کا استعمال کریں۔",
    menu_title: "مینو",
    reviews_title: "جائزے",
    post_review: "جائزہ پوسٹ کریں",
    open_scripts: "🗣️ گفتگو کے اسکرپٹس کھولیں",
    back_to_list: "⬅️ فہرست پر واپس",
    map_link: "📍 نقشہ دیکھیں",
    theme_light: "روشنی",
    theme_dark: "اندھیرا",
    theme_truetone: "سچ ٹون",
    rating_label: "درجہ بندی (0~5)",
    food_label: "کھایا ہوا کھانا",
    review_placeholder: "ایک ایماندارانہ جائزہ لکھیں (کم از کم 10 الفاظ)۔",
    loc_all: "تمام مقامات",
    loc_in_campus: "کیمپس میں",
    loc_out_campus: "کیمپس سے باہر"
  },
  mn: {
    top3_title: "Шилдэг 3",
    categories_title: "Ангилал",
    cat_all: "Бүгд",
    cat_restaurant: "Ресторан",
    cat_cafe: "Кафе",
    cat_others: "Бусад",
    modal_title: "Нөхцөл байдлын харилцан яриа",
    modal_desc: "Эдгээр хэллэгийг ашиглан хялбархан захиалга өгөөрэй.",
    menu_title: "Цэс",
    reviews_title: "Сэтгэгдэл",
    post_review: "Сэтгэгдэл үлдээх",
    open_scripts: "🗣️ Харилцан яриа нээх",
    back_to_list: "⬅️ Буцах",
    map_link: "📍 Газрын зураг",
    theme_light: "Гэрэлтэй",
    theme_dark: "Харанхуй",
    theme_truetone: "True Tone",
    rating_label: "Үнэлгээ (0~5)",
    food_label: "Идсэн хоол",
    review_placeholder: "Сэтгэгдлээ үлдээнэ үү (дор хаяж 10 үг).",
    loc_all: "Бүх байршил",
    loc_in_campus: "Сургууль дотор",
    loc_out_campus: "Сургуулийн гадна"
  },
  ne: {
    top3_title: "उत्कृष्ट ३",
    categories_title: "कोटीहरू",
    cat_all: "सबै",
    cat_restaurant: "रेस्टुरेन्ट",
    cat_cafe: "क्याफे",
    cat_others: "अन्य",
    modal_title: "अवस्था कुराकानी",
    modal_desc: "सजिलै अर्डर गर्न यी वाक्यांशहरू प्रयोग गर्नुहोस्।",
    menu_title: "मेनु",
    reviews_title: "समीक्षाहरू",
    post_review: "समीक्षा लेख्नुहोस्",
    open_scripts: "🗣️ कुराकानी खोल्नुहोस्",
    back_to_list: "⬅️ फर्कनुहोस्",
    map_link: "📍 नक्सा हेर्नुहोस्",
    theme_light: "हल्का",
    theme_dark: "गाढा",
    theme_truetone: "ट्रु टोन",
    rating_label: "मूल्याङ्कन (०~५)",
    food_label: "खाएको खाना",
    review_placeholder: "समीक्षा लेख्नुहोस् (कम्तीमा १० शब्दहरू)।",
    loc_all: "सबै स्थानहरू",
    loc_in_campus: "क्याम्पस भित्र",
    loc_out_campus: "क्याम्पस बाहिर"
  },
  vi: {
    top3_title: "Top 3",
    categories_title: "Danh mục",
    cat_all: "Tất cả",
    cat_restaurant: "Nhà hàng",
    cat_cafe: "Quán cà phê",
    cat_others: "Khác",
    modal_title: "Mẫu câu theo tình huống",
    modal_desc: "Sử dụng các mẫu câu này để gọi món dễ dàng.",
    menu_title: "Thực đơn",
    reviews_title: "Đánh giá",
    post_review: "Viết đánh giá",
    open_scripts: "🗣️ Mở mẫu câu",
    back_to_list: "⬅️ Quay lại",
    map_link: "📍 Xem bản đồ",
    theme_light: "Sáng",
    theme_dark: "Tối",
    theme_truetone: "True Tone",
    rating_label: "Đánh giá (0~5)",
    food_label: "Món đã ăn",
    review_placeholder: "Viết đánh giá của bạn (ít nhất 10 từ).",
    loc_all: "Tất cả vị trí",
    loc_in_campus: "Trong trường",
    loc_out_campus: "Ngoài trường"
  },
  si: {
    top3_title: "හොඳම 3",
    categories_title: "ප්‍රවර්ග",
    cat_all: "සියල්ල",
    cat_restaurant: "ආපනශාලාව",
    cat_cafe: "කැෆේ",
    cat_others: "වෙනත්",
    modal_title: "තත්ත්ව සංවාදය",
    modal_desc: "ඇණවුම් කිරීමට මෙම වාක්‍ය ඛණ්ඩ භාවිතා කරන්න.",
    menu_title: "මෙනුව",
    reviews_title: "සමාලෝචන",
    post_review: "සමාලෝචනයක් ලියන්න",
    open_scripts: "🗣️ සංවාද විවෘත කරන්න",
    back_to_list: "⬅️ ආපසු යන්න",
    map_link: "📍 සිතියම",
    theme_light: "ආලෝකය",
    theme_dark: "අඳුරු",
    theme_truetone: "සැබෑ තානය",
    rating_label: "ශ්‍රේණිගත කිරීම (0~5)",
    food_label: "කෑ කෑම",
    review_placeholder: "සමාලෝචනයක් ලියන්න (අවම වශයෙන් වචන 10 ක්).",
    loc_all: "සියලුම ස්ථාන",
    loc_in_campus: "කැම්පස් තුළ",
    loc_out_campus: "කැම්පස් පිටත"
  }
};